# HIER KANN MAN ZWISCHEN MYSQL UND SQLITE WECHSELN
DATABASE_TYPE = "sqlite" # mysql oder sqlite

# HIER KANN MAN EINSTELLEN, OB MAN IM ENTWICKLER-MODUS ODER IM PRODUKTIVBETRIEB IST
# IM ENTWICKLERMODUS WERDEN DETAILLIERTE FEHLERMELDUNGEN AUSGEGEBEN, IM PRODUKTIVMODUS NUR 
# DIE ALLGEMEINE FEHLERSEITE
ENVIRONMENT = "dev" # dev oder prod

MYSQL_HOST_IP = "127.0.0.1" # oder andere 
MYSQL_USERNAME = "flask_material"
MYSQL_PASSWORD = "DUMMY_PASSWORD" # DAS PASSWORD WIRD IN /etc/MATERIAL_CONFIG/credentials.toml gesetzt
MYSQL_DATABASE = "materialzeug"

SQLITE_DATABASE_FILENAME = "materialausgabe.db"
